CREATE TABLE IF NOT EXISTS companys ( 
    company_id Uuid PRIMARY KEY NOT NULL UNIQUE, 
    company_name varchar(255) NOT null, 
    company_street varchar(255) NOT null, 
    company_city varchar(255) NOT null, 
    company_zipcode varchar(10) NOT null, 
    company_country varchar(100) NOT null, 
    company_phone varchar(50) NOT null, 
    company_email varchar(255) NOT null, 
    company_website varchar(255) NOT NULL 
); 

CREATE TABLE IF NOT EXISTS company_contacts ( 
    contact_id Uuid PRIMARY KEY NOT NULL UNIQUE, 
    company Uuid NOT NULL, 
    firstname varchar(20) NOT null, 
    lastname varchar(20), 
    contact_email varchar(255) NOT null, 
    contact_phone varchar(50) NOT null, 
    contact_mobile varchar(50), 
    contact_titel varchar(50), 

    CONSTRAINT FK_company_contacts_company FOREIGN KEY (company) REFERENCES companys(company_id) 
); 

CREATE TABLE IF NOT EXISTS roles ( 
    role_id Uuid PRIMARY KEY NOT NULL UNIQUE, 
    role_name VARCHAR(50) NOT NULL UNIQUE, 
    create_orders BOOLEAN NOT NULL DEFAULT FALSE, 
    create_quotations BOOLEAN NOT NULL DEFAULT FALSE, 
    create_purchase_orders BOOLEAN NOT NULL DEFAULT FALSE, 
    create_articles BOOLEAN NOT NULL DEFAULT FALSE, 
    create_customers BOOLEAN NOT NULL DEFAULT FALSE, 
    create_suppliers BOOLEAN NOT NULL DEFAULT FALSE, 
    create_users BOOLEAN NOT NULL DEFAULT FALSE, 
    create_companys BOOLEAN NOT NULL DEFAULT FALSE 
); 

CREATE TABLE IF NOT EXISTS user_status_types ( 
    status_id INT generated BY default as identity PRIMARY KEY, 
    status_name VARCHAR(32) NOT NULL UNIQUE
); 

CREATE TABLE IF NOT EXISTS users ( 
    user_id Uuid PRIMARY KEY NOT NULL UNIQUE,
    password VARCHAR(255), -- for now not secured 
    email VARCHAR(64) NOT NULL UNIQUE, 
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    last_interaction_time TIMESTAMP not NULL default CURRENT_TIMESTAMP,
    role_id Uuid NOT NULL, 
    first_name VARCHAR(50) NOT NULL, 
    last_name VARCHAR(50) NOT NULL, 
    status int NOT NULL, 

    CONSTRAINT FK_users_role FOREIGN KEY (role_id) REFERENCES roles(role_id), 
    CONSTRAINT FK_users_status FOREIGN KEY (status) REFERENCES user_status_types(status_id)
);

CREATE TABLE IF NOT EXISTS authentication_tokens (
    token_id Uuid PRIMARY KEY NOT NULL UNIQUE,
    user_id Uuid NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,  -- hashed token
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expiration_time TIMESTAMP NOT NULL,
    last_used TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45) NOT NULL DEFAULT '',  
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);
